
server:
  port: 8000 #服务端口
spring:
  application:
    name: lion-dance-gateway
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848 #nacos服务地址
        service: lion-dance-gateway
    gateway:
      discovery:
        locator:
          enabled: true #使用服务发现路由
      routes:
        - id: lion-dance-data #设置路由id(理论上是可以随便写的)
          uri: lb://lion-dance-data #设置路由的url lb://nacos服务注册名称
          #uri: http://localhost:3302 #设置路由的url lb://nacos服务注册名称
          predicates:
            - Path=/api-data/** #路径匹配规则
          filters:
            - StripPrefix= 1